POST http://localhost:4000/api/v1/dettes
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibG9naW4iOiJ1c2VyMkBnbWFpbC5jb20iLCJyb2xlIjoiQk9VVElRVUlFUiIsImNsaWVudElkIjo0LCJpYXQiOjE3MjQwOTU4MzYsImV4cCI6MTcyNDA5OTQzNn0.3kL_1wsgargtNr6UgtHMTfEM72FtvsrOdQ0spyzzONY

{
  "clientId": 6,
  "montantVerser": 0,
  "articles": [
    {
      "articleId": 3,
      "quantiteArticleDette": 95
    },
        {
      "articleId": 4,
      "quantiteArticleDette": 123
    }
  ]
}

###

GET http://localhost:4000/api/v1/dettes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibG9naW4iOiJ1c2VyMkBnbWFpbC5jb20iLCJyb2xlIjoiQk9VVElRVUlFUiIsImNsaWVudElkIjo0LCJpYXQiOjE3MjQwOTU4MzYsImV4cCI6MTcyNDA5OTQzNn0.3kL_1wsgargtNr6UgtHMTfEM72FtvsrOdQ0spyzzONY

###

GET http://localhost:4000/api/v1/dettes/filter?statut=solde
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibG9naW4iOiJ1c2VyMkBnbWFpbC5jb20iLCJyb2xlIjoiQk9VVElRVUlFUiIsImNsaWVudElkIjo0LCJpYXQiOjE3MjQxMzg0MDcsImV4cCI6MTcyNDE0MjAwN30.ZhmHdLZ8VLzSnO8Mbxf4qn7aOaebcUhGeZxcWO4d0pc

###

GET http://localhost:4000/api/v1/dettes/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibG9naW4iOiJ1c2VyMkBnbWFpbC5jb20iLCJyb2xlIjoiQk9VVElRVUlFUiIsImNsaWVudElkIjo0LCJpYXQiOjE3MjQxMzg0MDcsImV4cCI6MTcyNDE0MjAwN30.ZhmHdLZ8VLzSnO8Mbxf4qn7aOaebcUhGeZxcWO4d0pc


###
POST http://localhost:4000/api/v1/dettes/date
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibG9naW4iOiJ1c2VyMkBnbWFpbC5jb20iLCJyb2xlIjoiQk9VVElRVUlFUiIsImNsaWVudElkIjo0LCJpYXQiOjE3MjQxMzg0MDcsImV4cCI6MTcyNDE0MjAwN30.ZhmHdLZ8VLzSnO8Mbxf4qn7aOaebcUhGeZxcWO4d0pc

{
  "date": "2024-08-19T19:43:41.094Z"
}