# POST - Créer un nouveau paiement
POST http://localhost:4000/api/v1/dettes/13/paiements
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibG9naW4iOiJ1c2VyN0BnbWFpbC5jb20iLCJyb2xlIjoiQk9VVElRVUlFUiIsImNsaWVudElkIjoxLCJpYXQiOjE3MjM4MzkxMTYsImV4cCI6MTcyMzg0MjcxNn0.G_Kmzadfq5zyB-UYaJfw_kwBLW6cXGZebyaE9YL0GeU


{
  "montant": 10000,
  "date": "2024-08-13T12:00:00.000Z"
}

###
# GET - Récupérer tous les paiements
GET http://localhost:4000/api/v1/dettes/11/paiements
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibG9naW4iOiJ1c2VyN0BnbWFpbC5jb20iLCJyb2xlIjoiQk9VVElRVUlFUiIsImlhdCI6MTcyMzY1NzUyNywiZXhwIjoxNzIzNjYxMTI3fQ.tf3FrvL_mueQk9ZrNjW9O4p1iwYYhKpMX_BmBuTN7aQ

###
GET http://localhost:4000/api/v1/dettes/2/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibG9naW4iOiJ1c2VyN0BnbWFpbC5jb20iLCJyb2xlIjoiQk9VVElRVUlFUiIsImlhdCI6MTcyMzY1OTMzMCwiZXhwIjoxNzIzNjYyOTMwfQ.hv_nXv3ZLY-77fF9sN_HMvrskySqoe8Ol9OtdoEVGvA

